name: Deploy website on push/merge

# Only trigger on PR/push and only for frontend files
on:
  # Trigger on PR close
  pull_request:
    types: [ closed ]
    branches:
      - master
    paths:
      - 'website/*.json'
      - 'website/*.js'
      - 'website/src/**'
      - 'website/modules/**'
      - '.github/workflows/deploy-website.yml'
  
  # Trigger on push to master (edge case, local merge)
  push:
    branches:
      - master
    paths:
      - 'website/*.json'
      - 'website/*.js'
      - 'website/src/**'
      - 'website/modules/**'
      - '.github/workflows/deploy-website.yml'

jobs:
  # Build the frontend giles
  build:
    name: Compile frontend

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
        working-directory: website

      - name: Set Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: npm i
        working-directory: website

      - name: Build website files
        env:
          NODE_ENV: production
        run: npm run build
        working-directory: website

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only=hosting
        env:
          GCP_SA_KEY: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      - name: Send push notification
        env:
          MSG_TITLE: "Success: OnionDAO Website"
          MSG_CONTENT: "website CI success"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        
      - name: Send failure push notification
        if: ${{ failure() }}
        env:
          MSG_TITLE: "Failure: OnionDAO Website"
          MSG_CONTENT: "website CI failed"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json